/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExtendableSearchBar: typeof import('./src/components/search/extendableSearchBar.vue')['default']
    Motion: typeof import('motion-v')['Motion']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search/searchBar.vue')['default']
    SearchHistory: typeof import('./src/components/search/searchHistory.vue')['default']
    SearchTag: typeof import('./src/components/search/searchTag.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
